<?php

function varnish_cache_menu() {
  return array(
    'admin/config/system/external_cache/varnish' => array(
      'title' => 'Varnish',
      'type' => MENU_LOCAL_TASK,
      'file' => 'varnish_cache.admin.inc',
      'access arguments' => array('cache wipe admin'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('varnish_cache_admin_settings'),
    )
  );
}

function varnish_cache_cache_wipe($paths) {
  module_load_include('inc', 'varnish_cache');
  $servers = _varnish_cache_get_cache_servers();
  foreach ($paths as $path) {
    foreach ($servers as $server) {
      _varnish_cache_purge($path, $server);
    }
  }
}

function varnish_cache_cache_wipe_all() {
  module_load_include('inc', 'varnish_cache');
  $servers = _varnish_cache_get_cache_servers();
  foreach ($servers as $server) {
    _varnish_cache_purge_all($server);
  }
}
